---
title: 2018 Enrollment - datatable function - DRAFT
author: Betsy Rosalen
date: '2019-12-19'
slug: /2018-enrollment/
categories: []
tags:
    - enrollment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')
library(kableExtra)
library(DT)
library(magrittr)
library(stringr)
```

```{r data}
# Import numerical data columns
data <- read.csv("S:/DicovererWorkbooks/Workbook2.csv", header=FALSE, stringsAsFactors = FALSE, skip = 5)

# Import headers
head1 <- c("", "", rep("Undergraduate",3), rep("Graduate",3), "")
head2 <- c("SenCom", "College", rep(c("Full-time", "Part-time", "Total"),2), "Total")

cols <- paste(head1, head2, sep = "<br/>", collapse = NULL)
cols[c(1, 2, 9)] = c("SenCom", "College", "Total")

# Set headers 
names(data) <- cols

# Make total rows uppercase
# data$SenCom <- toupper(data$SenCom)

# Combine first two columns
data$College <- ifelse(data$College == "", data$SenCom, data$College)
data <- data[-1]

# Calculate totals
data['Total<br/>Full-time'] <- rowSums(data[,c(2,5)], na.rm=TRUE)
data['Total<br/>Part-time'] <- rowSums(data[,c(3,6)], na.rm=TRUE)

# Reorder columns
data <- data[c(1:7,9,10,8)]

# Reorder rows
data <- data[c(2:19,1,21:27,20,28),]
row.names(data) <- NULL

# Rename Last row
data[c(19, 27, 28),1] <- c("SUBTOTAL SENIOR COLLEGES","SUBTOTAL COMMUNITY COLLEGES","TOTAL UNIVERSITY")

# ---------------------------------------------------------------------------- #
# Format numbers - DOES NOT WORK!!!
#data[2:10] <- format(data[2:10], big.mark   = ",")
#data[is.na.data.frame(data)] <- ""
# NONE OF THE ABOVE FORMATTING WORKS!  When done this way, can't stop NA from printing.
# ---------------------------------------------------------------------------- #

table_title <- "Total Enrollment by Undergraduate and Graduate Level, Full-time/Part-time Attendance, and College - Fall 2018"
```

```{r datatable, include=FALSE}
#'//////////////////////////////////////////////////////////////////////////////
#' FILE: datatable.R
#' AUTHOR: David Ruvolo
#' CREATED: 2019-12-05
#' MODIFIED: 2020-01-13
#' PURPOSE: build datatable function and helpers
#' STATUS: working
#' PACKAGES: htmltools
#' COMMENTS:
#'      The datatable function generates an html table from a dataset.
#'      This func returns a shiny tagList object which can be used in shiny
#'      applications, markdown documents, or written to an html file. The
#'      datatable function takes the following arguments.
#'
#'      ARGUMENTS:
#'      - data: the input dataset
#'      - id: an identifier for the table ideal for styling specific tables
#'            or for use in js
#'      - caption: a title for the table (recommended for accessible tables)
#'      - options:
#'          - responsive: a logical arg for turning on/off the rendering of
#'                      additional elements for responsive tables (i.e., span).
#'                      (Default = FALSE)
#'          - rowHeaders: a bool that renders the first cell of every row
#'              as a row header. This is useful for datasets where all data
#'              in a row is related, e.g., patient data. If set to TRUE,
#'              the data must be organized so that the row header is the
#'              first column.
#'
#'      ABOUT:
#'      The datatable function requires two helper functions: 1) to generate the
#'      table header and another used 2) to generate the table body. The func
#'      build_header() renders the <thead> element according to the input data.
#'      The build_body functions renders the table's <tbody> based on the input
#'      and the options. This function uses a nested lapplys to iterate each row
#'      and cell. If the responsive opt is TRUE, then the function will return
#'      a <span> element with the current cell's column name. <span> has
#'      the class `hidden-colname` that hides/shows the element based on screen
#'      size (see datatable.css). Role attributes are added in the event
#'      the display properties are altered in css.
#'//////////////////////////////////////////////////////////////////////////////

# ~ 1 ~
# DEFINE HELPER FUNCTIONS
datatable_helpers <- list()

# ~ a ~
# FUNCTION: build_header
datatable_helpers$build_header <- function(data, options) {
    columns <- colnames(data)
    cells <- lapply(1:length(columns), function(n) {

        # define cell content: as html or text
        if (isTRUE(options$asHTML)) {
            cell_value <- htmltools::HTML(columns[n])
        } else {
            cell_value <- columns[n]
        }

        # build header
        cell <- htmltools::tags$th(scope = "col", cell_value)
        cell
    })

    # return header
    htmltools::tags$thead(
        htmltools::tags$tr(role = "row", cells)
    )
}

# ~ b ~
# FUNCTION: build_body
datatable_helpers$build_body <- function(data, options) {
    body <- lapply(1:NROW(data), function(row) {
        cells <- lapply(1:NCOL(data), function(col) {

            # process options: render as html or escape?
            if (isTRUE(options$asHTML)) {
                cell_value <- htmltools::HTML(data[row, col])
            } else {
                cell_value <- data[row, col]
            }

            # process options$rowHeaders (this generates the cell)
            if (isTRUE(options$rowHeaders) && col == 1) {
                if (isTRUE(options$responsive)) {
                    cell <- htmltools::tags$th(role = "rowheader")
                    cell$children <- list(
                        htmltools::tags$span(
                            class = "hidden-colname",
                            `aria-hidden` = "true",
                            htmltools::HTML(colnames(data)[col])
                        ),
                        cell_value
                    )
                } else {
                    cell <- htmltools::tags$th(role = "rowheader", cell_value)
                }
            } else {
                cell <- htmltools::tags$td(role = "cell", datavalue=cell_value)
                # process options: responsive
                if (isTRUE(options$responsive)) {
                    cell$children <- list(
                        htmltools::tags$span(
                            class = "hidden-colname",
                            `aria-hidden` = "true",
                            htmltools::HTML(gsub("<br/>", " - ", colnames(data)[col]))
                        )
                    )
                } 
            }

            # return cell
            cell
        })
#################################################################################
##### Added 'totals = "yes"' to rows that contain the word total in the row header  
##### so that they can be styled by the css stylesheet...
        
        #print(grepl("total", as.character(cells[[1]]), ignore.case = TRUE))
        if (grepl("subtotal", as.character(cells[[1]]), ignore.case = TRUE)) {
            htmltools::tags$tr(role = "row", subtotals = "yes", cells)
        } else if (grepl("total", as.character(cells[[1]]), ignore.case = TRUE)) {
            htmltools::tags$tr(role = "row", totals = "yes", cells)
        } else {
            htmltools::tags$tr(role = "row", cells)
        }
        
        # return cells in a row
        #htmltools::tags$tr(role = "row", cells)
#################################################################################
    })
 
    # return body
    htmltools::tags$tbody(body)
}

#'////////////////////////////////////////

# ~ 2 ~
# FUNCTION: datatable
datatable <- function(data, id = NULL, caption = NULL, options = list(responsive = FALSE, rowHeaders = TRUE, asHTML = TRUE)) {

    # render table and table elements
    tbl <- htmltools::tags$table(class = "datatable",
        datatable_helpers$build_header(data, options),
        datatable_helpers$build_body(data, options)
    )

    # add id
    if (!is.null(id)) {
        tbl$attribs$id <- paste0("datatable-", id)
    }

    # should a caption be rendered?
    if (!is.null(caption)) {
        tbl$children <- list(
            htmltools::tags$caption(caption),
            tbl$children
        )
    }

    # return
    tbl
}
```

```{r}
# ---------------------------------------------------------------------------- #
# Format numbers and remove NA's
# data[is.na(data)] <- NULL
data3 <- data
data3[2:10] <- format(data3[2:10], big.mark   = ",")
data3$`Undergraduate<br/>Full-time` <- str_replace_all(data3$`Undergraduate<br/>Full-time`, ".+NA", "0")
data3$`Undergraduate<br/>Part-time` <- str_replace_all(data3$`Undergraduate<br/>Part-time`, ".+NA", "0")
data3$`Undergraduate<br/>Total` <- str_replace_all(data3$`Undergraduate<br/>Total`, ".+NA", "0")
data3$`Graduate<br/>Full-time` <- str_replace_all(data3$`Graduate<br/>Full-time`, ".+NA", "0")
data3$`Graduate<br/>Part-time` <- str_replace_all(data3$`Graduate<br/>Part-time`, ".+NA", "0")
data3$`Graduate<br/>Total` <- str_replace_all(data3$`Graduate<br/>Total`, ".+NA", "0")
data3$`Total<br/>Full-time` <- str_replace_all(data3$`Total<br/>Full-time`, ".+NA", "0")
data3$`Total<br/>Part-time` <- str_replace_all(data3$`Total<br/>Part-time`, ".+NA", "0")
data3$Total <- str_replace_all(data3$Total, ".+NA", "0")
# THIS IS REALLY NASTY BUT IT WORKS!
# ---------------------------------------------------------------------------- #
```

###### Accessibility Instructions: This table contains `r table_title`.  Footnotes display immediately below the table. 

```{r output}
t <- datatable(data3, id="Enrollment Test", caption = table_title, 
               options = list(responsive = TRUE, rowHeaders = TRUE, asHTML = TRUE))
#writeLines(as.character(t), "S:/R/Enrollment_datatable.html")
#cat(as.character(t))
t
```

##### Note: Enrollment for Guttman, Kingsborough, and LaGuardia are preliminary; final enrollment will be available in March.

